config/routes.rb
Rails.application.routes.draw do
  resources :examples
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: %i[ show edit update destroy ]

  # GET /examples or /examples.json
  def index
    @examples = []
  end

  # GET /examples/1 or /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples or /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to example_url(@example), notice: "Example was successfully created." }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1 or /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to example_url(@example), notice: "Example was successfully updated." }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1 or /examples/1.json
  def destroy
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url, notice: "Example was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def example_params
      params.fetch(:example, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_example.html.erb
<div id="<%= dom_id example %>">
</div>

app/views/examples/_form.html.erb
<%= form_with(model: example) do |form| %>
  <% if example.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
        <% example.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Show this example", @example %> |
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Examples</h1>

<div id="examples">
  <% @examples.each do |example| %>
    <%= render example %>
    <p>
      <%= link_to "Show this example", example %>
    </p>
  <% end %>
</div>

<%= link_to "New example", new_example_path %>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @example %>

<div>
  <%= link_to "Edit this example", edit_example_path(@example) %> |
  <%= link_to "Back to examples", examples_path %>

  <%= button_to "Destroy this example", @example, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- 

Following line attempts to fix Apollo Client Devtools breaking importmaps, but doesn't work properly.

See:

- https://github.com/WICG/import-maps/issues/248#issuecomment-1047373384
- https://github.com/guybedford/es-module-shims

-->
<script async src="https://ga.jspm.io/npm:es-module-shims@1.4.6/dist/es-module-shims.js"></script>
<html>
  <head>
    <title>RailsImportmapExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>